services:
  db:
    image: postgres:16
    container_name: fluxurl-db
    environment:
      POSTGRES_USER: fluxurl
      POSTGRES_PASSWORD: fluxurl
      POSTGRES_DB: fluxurl
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluxurl -d fluxurl"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: fluxurl:latest
    container_name: fluxurl-migrate
    environment:
      DATABASE_URL: postgresql+asyncpg://fluxurl:fluxurl@db:5432/fluxurl
    command: ["alembic", "upgrade", "head"]
    depends_on:
      db:
        condition: service_healthy

  app:
    image: fluxurl:latest
    container_name: fluxurl-app
    environment:
      DATABASE_URL: postgresql+asyncpg://fluxurl:fluxurl@db:5432/fluxurl
      BASE_URL: http://13.201.2.41
    ports:
      - "80:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata: