# Web Server Configuration
server.port=8081

# Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fluxurl}
spring.datasource.username=${DATABASE_USER:fluxurl}
spring.datasource.password=${DATABASE_PASSWORD:fluxurl}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "update" will auto-create/update tables on app startup
spring.jpa.hibernate.ddl-auto=update
# Prints generated SQL to console (great for debugging Hibernate queries)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Custom App Configurations
app.base-url=${BASE_URL:http://localhost:8081}